name: Add Copyright Information Action
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
         path: parakeet
      - name: Clone python script repo
        uses: actions/checkout@v2
        with:
         repository: 'MechaSpin/parakeet-devtools'
         path: 'parakeet-devtools'
         token: ${{ secrets.DEVTOOLS_ACCESS_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: execute copyright python script
        run: |
          python ./parakeet-devtools/parakeet_copyright.py
      - name: Push changes to git
        run: |
          cd parakeet/
          git config --global user.name 'CopyrightGitHubAction'
          git config --global user.email 'build@mechaspin.com'
          git commit -am "Add Copyright Information" || exit 0
          git push