name: Build-Distributable-Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      
    - name: Clone Parkeet SDK
      uses: actions/checkout@v2
      with:
        repository: 'BryceVichiOJ/parakeet-sdk'
        path: 'parakeet-sdk'
        token: ${{ secrets.Parakeet_PAT || github.token }}
        
    - name: Configure CMake for Parakeet SDK
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: 
        cd parakeet-sdk &&
        cmake -B ${{github.workspace}}/parakeet-sdk/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/parakeet-sdk/install

    - name: Build for Parakeet SDK
      # Build your program with the given configuration
      run: 
        cmake --build parakeet-sdk/build --config ${{env.BUILD_TYPE}} --target install &&
        cd parakeet-sdk/build
        
    - name: Clone Parkeet Qt
      uses: actions/checkout@v2
      with:
        repository: 'BryceVichiOJ/parakeet-qt'
        path: 'parakeet-qt'
        token: ${{ secrets.Parakeet_PAT || github.token }}
        
    - name: Configure CMake for Parakeet Qt
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run:
        cd parakeet-qt &&
          cmake -B ${{github.workspace}}/parakeet-qt/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH=${{github.workspace}}/parakeet-sdk/install &&
          cd build

    - name: Build for Parakeet Qt
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/parakeet-qt/build --config ${{env.BUILD_TYPE}}
      
  # CREATE DISTRIBUATABLE AND UPLOAD IT
